//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        public int LoadSession { get; set; }
        public string HSU_ID { get; set; }
        public int WasherID { get; set; }
        public System.TimeSpan Load_Start { get; set; }
        public System.TimeSpan Load_Finish { get; set; }
    
        public virtual UsersDB UsersDB { get; set; }
        public virtual WasherDB WasherDB { get; set; }
    }
}
