//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WasherDBEntities : DbContext
    {
        public WasherDBEntities()
            : base("name=WasherDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DryersDB> DryersDBs { get; set; }
        public virtual DbSet<Load> Loads { get; set; }
        public virtual DbSet<RatingsDB> RatingsDBs { get; set; }
        public virtual DbSet<UsersDB> UsersDBs { get; set; }
        public virtual DbSet<WasherDB> WasherDBs { get; set; }
    }
}
